#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/probando1?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    name: 
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8099/eureka/
