#Application Configuration
server:
  port: 8092
  error:
    include-message: always
    include-binding-errors: always
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/probando1?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    name: 

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    #show-sql: true
    #hibernate:
      #ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        #show_sql: true
        #use_sql_comments: false
        #format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8099/eureka/

